site_name: openai-responses
repo_url: https://github.com/mharrisb1/openai-responses-python
theme:
  name: material
  features:
    - toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
    - content.code.select
    - content.code.annotate
    - content.code.copy
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - toc:
      permalink: true
      title: On this page
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - index.md
  - User Guide:
      - user_guide/index.md
      - user_guide/mockers.md
      - user_guide/chaining.md
      - user_guide/state.md
  - Endpoints:
      - endpoints/index.md
      - endpoints/chat.md
      - endpoints/embeddings.md
      - endpoints/files.md
      - endpoints/assistants.md
      - endpoints/threads.md
      - endpoints/messages.md
      - endpoints/runs.md
